version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - rbc
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - rbc
    volumes:
      - ./backend/app:/app/app
      - ./backend/entrypoint.sh:/app/entrypoint.sh
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6
    ports:
      - "54386:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - rbc

  redis:
    image: redis:7
    networks:
      - rbc

volumes:
  mongo-data:
networks:
  rbc:

